/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab8p2_andrefloresgerardohasbum;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 *
 *
 * @author ghasb
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public ArrayList<User> usuarios = new ArrayList();
    public ArrayList<Torneo> torneos = new ArrayList();
    private boolean logged = false;
    public User usuarioEnUso = new User();

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrearTorneo = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nombreTorneo = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jbTerminarCrearTorneo = new javax.swing.JButton();
        jd_Registrar = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Tf_usernameRegistrar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tf_PasswordRegistrar = new javax.swing.JTextField();
        rb_Admin = new javax.swing.JRadioButton();
        rb_Participante = new javax.swing.JRadioButton();
        jbCrear = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        LoginAdmin = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jbSalirAdmin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbCrearTorneo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        LoginParticipante = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jbSalirParticipante = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jbUnirseTorneo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LoginConfirm = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tf_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tf_Password = new javax.swing.JTextField();

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 570));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre del Torneo");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Rondas");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));
        jPanel9.add(tf_nombreTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, 20));
        jPanel9.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 120, 30));

        jbTerminarCrearTorneo.setBackground(new java.awt.Color(0, 0, 204));
        jbTerminarCrearTorneo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbTerminarCrearTorneo.setText("Crear Torneo");
        jbTerminarCrearTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTerminarCrearTorneoMouseClicked(evt);
            }
        });
        jPanel9.add(jbTerminarCrearTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 130, 80));

        javax.swing.GroupLayout CrearTorneoLayout = new javax.swing.GroupLayout(CrearTorneo.getContentPane());
        CrearTorneo.getContentPane().setLayout(CrearTorneoLayout);
        CrearTorneoLayout.setHorizontalGroup(
            CrearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CrearTorneoLayout.setVerticalGroup(
            CrearTorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 570));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre de Usuario");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 30));

        Tf_usernameRegistrar.setBackground(new java.awt.Color(153, 153, 153));
        Tf_usernameRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(Tf_usernameRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 210, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 180, 30));

        Tf_PasswordRegistrar.setBackground(new java.awt.Color(153, 153, 153));
        Tf_PasswordRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(Tf_PasswordRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 210, 50));

        rb_Admin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rb_Admin.setForeground(new java.awt.Color(0, 0, 0));
        rb_Admin.setText("Administrador");
        jPanel3.add(rb_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        rb_Participante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rb_Participante.setForeground(new java.awt.Color(0, 0, 0));
        rb_Participante.setText("Participante");
        jPanel3.add(rb_Participante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jbCrear.setBackground(new java.awt.Color(255, 0, 0));
        jbCrear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbCrear.setForeground(new java.awt.Color(255, 255, 255));
        jbCrear.setText("Crear");
        jbCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCrearMouseClicked(evt);
            }
        });
        jPanel3.add(jbCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 483, 90, 60));

        javax.swing.GroupLayout jd_RegistrarLayout = new javax.swing.GroupLayout(jd_Registrar.getContentPane());
        jd_Registrar.getContentPane().setLayout(jd_RegistrarLayout);
        jd_RegistrarLayout.setHorizontalGroup(
            jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_RegistrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jd_RegistrarLayout.setVerticalGroup(
            jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 0, 51));

        jbSalirAdmin.setBackground(new java.awt.Color(0, 51, 204));
        jbSalirAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSalirAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jbSalirAdmin.setText("Salir");
        jbSalirAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSalirAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jbSalirAdmin)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addComponent(jbSalirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 570));
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 160, 60));

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 330));

        jList2.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jList2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 180, 330));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Torneos");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Personas dentro del torneo");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jbCrearTorneo.setBackground(new java.awt.Color(51, 51, 255));
        jbCrearTorneo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCrearTorneo.setText("Crear Torneo");
        jbCrearTorneo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCrearTorneoMouseClicked(evt);
            }
        });
        jPanel5.add(jbCrearTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 160, 70));

        jButton5.setBackground(new java.awt.Color(0, 51, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Salir");

        javax.swing.GroupLayout LoginAdminLayout = new javax.swing.GroupLayout(LoginAdmin.getContentPane());
        LoginAdmin.getContentPane().setLayout(LoginAdminLayout);
        LoginAdminLayout.setHorizontalGroup(
            LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginAdminLayout.createSequentialGroup()
                    .addGap(277, 277, 277)
                    .addComponent(jButton5)
                    .addContainerGap(278, Short.MAX_VALUE)))
        );
        LoginAdminLayout.setVerticalGroup(
            LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LoginAdminLayout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(250, Short.MAX_VALUE)))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 0, 51));

        jbSalirParticipante.setBackground(new java.awt.Color(0, 51, 204));
        jbSalirParticipante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSalirParticipante.setForeground(new java.awt.Color(255, 255, 255));
        jbSalirParticipante.setText("Salir");
        jbSalirParticipante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSalirParticipanteMouseClicked(evt);
            }
        });
        jbSalirParticipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirParticipanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jbSalirParticipante)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(jbSalirParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 570));
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 160, 60));

        jList3.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jList3);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, 330));

        jList4.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jList4);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 110, 330));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Torneos Disponibles");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Torneos Ganados");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jList5.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jList5);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 120, 330));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Torneos Cerrados");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jbUnirseTorneo.setBackground(new java.awt.Color(0, 51, 204));
        jbUnirseTorneo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbUnirseTorneo.setForeground(new java.awt.Color(255, 255, 255));
        jbUnirseTorneo.setText("Unirse al Torneo");
        jPanel7.add(jbUnirseTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        javax.swing.GroupLayout LoginParticipanteLayout = new javax.swing.GroupLayout(LoginParticipante.getContentPane());
        LoginParticipante.getContentPane().setLayout(LoginParticipanteLayout);
        LoginParticipanteLayout.setHorizontalGroup(
            LoginParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        LoginParticipanteLayout.setVerticalGroup(
            LoginParticipanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 570));

        LoginConfirm.setBackground(new java.awt.Color(204, 0, 0));
        LoginConfirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginConfirm.setText("Iniciar sesion");
        LoginConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginConfirmMouseClicked(evt);
            }
        });
        jPanel1.add(LoginConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 150, 70));

        SignUpButton.setBackground(new java.awt.Color(0, 51, 204));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpButton.setText("Registrar");
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
        });
        jPanel1.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 150, 70));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 160, 60));

        Tf_username.setBackground(new java.awt.Color(153, 153, 153));
        Tf_username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 210, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre de Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 180, 30));

        Tf_Password.setBackground(new java.awt.Color(153, 153, 153));
        Tf_Password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Tf_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        this.setVisible(false);
        jd_Registrar.pack();
        jd_Registrar.setLocationRelativeTo(this);
        jd_Registrar.setVisible(true);
        jd_Registrar.setResizable(false);
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void jbCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCrearMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        jd_Registrar.setVisible(false);

        if (rb_Admin.isSelected()) {
            usuarios.add(new Admin(Tf_usernameRegistrar.getText(), Tf_PasswordRegistrar.getText(), 0));

        } else if (rb_Participante.isSelected()) {
            usuarios.add(new Participante(Tf_usernameRegistrar.getText(), Tf_PasswordRegistrar.getText()));
        }
        this.setVisible(true);
        escribirUsuarios(usuarios, "usuarios.bin");

        JOptionPane.showMessageDialog(this, "Registro de Usuario terminado con exito");


    }//GEN-LAST:event_jbCrearMouseClicked

    private void LoginConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginConfirmMouseClicked
        // TODO add your handling code here:
        usuarios = leerUsuarios("usuarios.bin");

        String nombreUsuario = Tf_username.getText();
        String contrasenia = Tf_Password.getText();

        for (User usuario : usuarios) {
            if (nombreUsuario.equals(usuario.getNombre()) && contrasenia.equals(usuario.getPassword())) {
                usuarioEnUso = usuario;
                logged = true;
                break;
            }
        }

        if (logged) {
            if (usuarioEnUso instanceof Participante) {
                this.setVisible(false);

                LoginParticipante.setVisible(true);
                LoginParticipante.pack();
                LoginParticipante.setResizable(false);

            } else if (usuarioEnUso instanceof Admin) {
                this.setVisible(false);

                LoginAdmin.setVisible(true);
                LoginAdmin.pack();
                LoginAdmin.setResizable(false);

            }

        }


    }//GEN-LAST:event_LoginConfirmMouseClicked

    private void jbSalirAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalirAdminMouseClicked
        // TODO add your handling code here:
        LoginAdmin.setVisible(false);
        this.pack();
        this.setVisible(true);
    }//GEN-LAST:event_jbSalirAdminMouseClicked

    private void jbSalirParticipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirParticipanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalirParticipanteActionPerformed

    private void jbSalirParticipanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalirParticipanteMouseClicked
        // TODO add your handling code here:LoginAdmin.setVisible(false);
        LoginParticipante.setVisible(false);
        this.pack();
        this.setVisible(true);
        
    }//GEN-LAST:event_jbSalirParticipanteMouseClicked

    private void jbTerminarCrearTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTerminarCrearTorneoMouseClicked
        // TODO add your handling code here:
        torneos.add(new Torneo(tf_nombreTorneo.getText(), true, false));

        escribirTorneos(torneos, "torneos.bin");

        JOptionPane.showMessageDialog(this, "Registro de torneo terminado con exito");
        CrearTorneo.setVisible(false);
        LoginAdmin.setVisible(true);
        LoginAdmin.pack();
    }//GEN-LAST:event_jbTerminarCrearTorneoMouseClicked

    private void jbCrearTorneoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCrearTorneoMouseClicked
        // TODO add your handling code here:
        
        LoginAdmin.setVisible(false);
        CrearTorneo.pack();
        CrearTorneo.setVisible(true);
        
    }//GEN-LAST:event_jbCrearTorneoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public static void escribirUsuarios(ArrayList<User> usuarios, String nombreArchivo) {
        try (ObjectOutputStream OOS = new ObjectOutputStream(new FileOutputStream(nombreArchivo))) {
            OOS.writeObject(usuarios);
            System.out.println("usuario guardado.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static ArrayList<User> leerUsuarios(String nombreArchivo) {
        ArrayList<User> usuarios = new ArrayList();
        try (ObjectInputStream OIS = new ObjectInputStream(new FileInputStream(nombreArchivo))) {
            usuarios = (ArrayList<User>) OIS.readObject();
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        return usuarios;
    }
    
    public static void escribirTexto(ArrayList<Torneo> lista, String path) throws IOException{
        
        FileWriter fw = null;
        BufferedWriter bw = null;
        
        try {
            
            fw = new FileWriter(path, false);
            bw = new BufferedWriter(fw);
            
            for ( Torneo a : lista) {
                    Torneo temp = (Torneo) a;
                    bw.write("EL participante "+temp.getGanador().getNombre()+" ha ganado el torneo "+temp.getNombre());
            }
            bw.flush();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        bw.close();
        fw.close();
        
    }
    
    public static void escribirTorneos(ArrayList<Torneo> torneos, String nombreArchivo) {
        try (ObjectOutputStream OOS = new ObjectOutputStream(new FileOutputStream(nombreArchivo))) {
            OOS.writeObject(torneos);
            System.out.println("Torneo guardado.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static ArrayList<Torneo> leerTorneos(String nombreArchivo) {
        ArrayList<Torneo> torneos = new ArrayList();
        try (ObjectInputStream OIS = new ObjectInputStream(new FileInputStream(nombreArchivo))) {
            torneos = (ArrayList<Torneo>) OIS.readObject();
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        return torneos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CrearTorneo;
    private javax.swing.JDialog LoginAdmin;
    private javax.swing.JButton LoginConfirm;
    private javax.swing.JDialog LoginParticipante;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JTextField Tf_Password;
    private javax.swing.JTextField Tf_PasswordRegistrar;
    private javax.swing.JTextField Tf_username;
    private javax.swing.JTextField Tf_usernameRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton jbCrear;
    private javax.swing.JButton jbCrearTorneo;
    private javax.swing.JButton jbSalirAdmin;
    private javax.swing.JButton jbSalirParticipante;
    private javax.swing.JButton jbTerminarCrearTorneo;
    private javax.swing.JButton jbUnirseTorneo;
    private javax.swing.JDialog jd_Registrar;
    private javax.swing.JRadioButton rb_Admin;
    private javax.swing.JRadioButton rb_Participante;
    private javax.swing.JTextField tf_nombreTorneo;
    // End of variables declaration//GEN-END:variables
}
